"""constant"""

NUMERICAL_TYPE = "num"
NUMERICAL_PREFIX = "n_"

CATEGORY_TYPE = "cat"
CATEGORY_PREFIX = "c_"

TIME_TYPE = "time"
TIME_PREFIX = "t_"

JOBS = 4
MAX_COMBINE_NUMS = 5
MAX_COMBINE_CATS = 5

type2prefix = {
    NUMERICAL_TYPE:NUMERICAL_PREFIX,
    CATEGORY_TYPE:CATEGORY_PREFIX,
    TIME_TYPE:TIME_PREFIX,
}
SEED = 1

MAX_FEATURE_NUMBER = 500

IF_ANALYSE = True
DROP_HIGH_CHG_RT = True
HIGH_CHG_RT_FLOOR = 0.5
HIGH_CHG_RT_USED_FOR_DIFF = False
IF_SORT_VALID_AUC = False




